### ISSUE TITLE
aws/cloudformation/sam-template.yml is missing

### ISSUE THREAD

**Issue by fletling** [rynop/abp-sam-nestjs#2]
I'm attempting to run `make run/sam-start-api` that then throws a `Error: Template file not found`. 

It appears that this command runs a `sam local start-api -t aws/cloudformation/sam-template.yml` but that template file does indeed not exist.

**Comment by rynop** [comment]
oops - sorry about that.  Forgot to commit it.  https://github.com/rynop/abp-sam-nestjs/commit/6bc185f9fd8e2ec29214baf984e1719d491ee0fd fixes this.

Thanks!

**Comment by fletling** [comment]
awesome. thanks :)
